site_name: XeFramework - Just another WordPress framework

repo_name: XeCreators/xe-framework
repo_url: https://github.com/XeCreators/xe-framework
edit_uri: ''

nav:
  - Getting Started:
    - Introduction: index.md
    - Let's Start: start.md
    - Automation: automation.md
    - Manual Use: manual.md
  - Models:
    - Theme Options: theme_options.md
    - Page Options: page_options.md
    - Customizer: customizer.md
    - Widgets: widgets.md
  - Views:
    - Introduction: views.md
    - Header: header.md
    - Footer: footer.md
    - Archive: archive.md
    - Single: single.md
    - Content Page: content_page.md
    - Content None: content_none.md
  - Controllers:
    - Setup and Enqueue Scripts: functions.md
    - Template Tags: template_tags.md
    - Extra Fucntions: extras.md
    - Class Theme Options: class_to.md
    - Class Dynamic Styles: styles.md
    - Class Dynamic Scripts: scripts.md
  - Helpers:
    - Class Defaults: defaults.md
    - Class Selectors: selectors.md
    - Class Helpers: helpers.md
    - Class Demo Content: demo_content.md
    - Plugins Activator: plugins.md
  - Support: support.md

theme: 
  name: material
  features:
    - navigation.tabs

markdown_extensions:
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic:
      mode: view

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/XeCreators
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/XeCreators
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/xecreatorsit
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/XeCreators
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/xecreators/